src/main/java/edu/iit/sat/itmd4515/adamarjian/domain/Player.java
package edu.iit.sat.itmd4515.adamarjian.domain;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import edu.iit.sat.itmd4515.adamarjian.security.User;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

/**
 *
 * @author EXO
 */
@Entity
@Table(name = "player")
@NamedQueries({
    @NamedQuery(
            name = "Player.findByName",
            query = "select p from Player p where p.name = :name"),
    @NamedQuery(
            name = "Player.findAll",
            query = "select p from Player p"),
        @NamedQuery(
            name = "Player.findByUsername",
            query = "select p from Player p where p.user.userName = :username")
})
public class Player extends AbstractIdentifiedEntity {
    
    @ManyToOne
    @JoinColumn(name = "Bank_ID")
    private Bank bank;
    

    @NotBlank
    private String name;

    @Email
    @NotBlank
    @Column(name = "email")
    private String email;
    
    @OneToOne
    @JoinColumn(name = "USERNAME")
    private User user;

    @Column(name = "birthday")
    @Temporal(TemporalType.DATE)
    private Date birthday;

    
    
    @ManyToMany(mappedBy = "players")
    private List<VideoGame> videogames= new ArrayList<>();
    
    

    public Player() {
    }



    public Player(String name, String email, Date birthday) {
        this.name = name;
        this.email = email;
        this.birthday = birthday;
    }

    /**
     * Get the value of name
     *
     * @return the value of name
     */
    public String getName() {
        return name;
    }

    /**
     * Set the value of name
     *
     * @param name new value of name
     */
    public void setName(String name) {
        this.name = name;
    }

  

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    
    
    public void removeBank(){
        this.bank.getPlayers().remove(this);
        this.bank = null;
    }
    
    public Bank getBank() {
        return bank;
    }
    public void setBank(Bank bank) {
        this.bank = bank;
        
         if (!this.bank.getPlayers().contains(this)) {
            this.bank.getPlayers().add(this);
        }
        
        
    }
    
    
    

    
    public List<VideoGame> getVideogames() {
        return videogames;
    }
    public void setVideogames(List<VideoGame> videogames) {
        this.videogames = videogames;
    }
    public User getUser() {
        return user;
    }
    public void setUser(User user) {
        this.user = user;
    }

    @Override
    public String toString() {
        return "Player{" + "bank=" + bank + ", name=" + name + ", email=" + email + ", user=" + user + ", birthday=" + birthday + ", videogames=" + videogames + '}';
    }

}

src/main/java/edu/iit/sat/itmd4515/adamarjian/web/LoginController.java
package edu.iit.sat.itmd4515.adamarjian.web;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotBlank;


@Named
@RequestScoped
public class LoginController extends AbstractController {

    private static final Logger LOG = Logger.getLogger(LoginController.class.getName());

    @NotBlank(message = "You must enter a username")
    private String username;
    @NotBlank(message = "You must enter a password")
    private String password;

    public LoginController() {
    }

 
    public String doLogin() {
        try {
            HttpServletRequest req = (HttpServletRequest) context.getExternalContext().getRequest();
            req.login(username, password);
            return "/welcome?faces-redirect=true";
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
            context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Bad Login", "Please check your username or password and try again."));
            return "/login";
        }
    }

    public String doLogout() {
        try {
            HttpServletRequest req = (HttpServletRequest) context.getExternalContext().getRequest();
            req.logout();

        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, null, ex);
        }

        return "/login?faces-redirect=true";

    }


    public String getRemoteUser() {
        return context.getExternalContext().getRemoteUser();
    }

    public boolean isParent() {
        return context.getExternalContext().isUserInRole("PARENT_ROLE");
    }

    public boolean isPlayer() {
        return context.getExternalContext().isUserInRole("PLAYER_ROLE");
    }

    public boolean isAdmin() {
        return context.getExternalContext().isUserInRole("ADMIN_ROLE");
    }

    /**
     * Get the value of username
     *
     * @return the value of username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Set the value of username
     *
     * @param username new value of username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}

src/main/java/edu/iit/sat/itmd4515/adamarjian/web/PlayerController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.adamarjian.web;

import edu.iit.sat.itmd4515.adamarjian.domain.Player;
import edu.iit.sat.itmd4515.adamarjian.domain.VideoGame;
import edu.iit.sat.itmd4515.adamarjian.service.PlayerService;
import edu.iit.sat.itmd4515.adamarjian.service.VideoGameService;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author adama
 */
@Named
@RequestScoped
public class PlayerController extends AbstractController {

    private static final Logger LOG = Logger.getLogger(PlayerController.class.getName());

    private Player player;
     private VideoGame videoGame;


    @EJB private PlayerService playerSvc;
    
    @EJB private VideoGameService VideoGameSvc;

    @Inject
    private LoginController loginController;
   
    

    @Override
    @PostConstruct
    protected void postConstruct() {
        super.postConstruct();
        LOG.info("Inside PlayerController postConstruct");
        player = playerSvc.findByUserName(loginController.getRemoteUser());
        videoGame = new VideoGame();
    }
    
    // helper method
    public String getGamePlayerSFormatted(VideoGame game){
        List<String> names = new ArrayList<>();
        for(Player player : game.getPlayers()){
            names.add(player.getName());
        }
        return String.join(",", names);
    }

    //place action methods here
    public String doViewGame(VideoGame game){
        this.videoGame = game;
        LOG.info("We are about to view the information for VideoGame " + videoGame.toString());
        return "/player/viewGame";
    }
    
    // TODO
    public String doEditGame(VideoGame game){
         this.videoGame = game;
        LOG.info("We are about to edit the information for VideoGame " + videoGame.toString());
        return "/player/editGame";
    }
    
    // TODO
    public String doDeleteGame(){
        LOG.info("We are about to delete the information for VideoGame " + videoGame.toString());
        return "/player/welcome";
    }

    // TODO
    public String doCreateGame(){
        LOG.info("We are about to create a new VideoGame" + videoGame.toString());
        return "/player/welcome";
    }

    public String executeSavePlayer() {
        LOG.info("Inside PlayerController executeSavePlayer to save"  + this.player.toString());
        return "/player/welcome";
    }
    public String executeSaveVideoGame() {
        LOG.info("Inside DiscJockeyController executeSaveRadioShow to save " + this.videoGame.toString());
        VideoGameSvc.update(videoGame);
        return "/player/welcome";
    }

    /**
     * Get the value of player
     *
     * @return the value of player
     */
    public Player getPlayer() {
        return player;
    }

    /**
     * Set the value of player
     *
     * @param player new value of player
     */
    public void setPlayer(Player player) {
        this.player = player;
    }
    public VideoGame getVideoGame() {
        return videoGame;
    }
    public void setVideoGame(VideoGame videoGame) {
        this.videoGame = videoGame;
    }

}

src/main/java/edu/iit/sat/itmd4515/adamarjian/web/PlayerServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.adamarjian.web;

import edu.iit.sat.itmd4515.adamarjian.domain.Bank;
import edu.iit.sat.itmd4515.adamarjian.domain.Player;
import edu.iit.sat.itmd4515.adamarjian.domain.VideoGame;
import edu.iit.sat.itmd4515.adamarjian.service.BankService;
import edu.iit.sat.itmd4515.adamarjian.service.PlayerService;
import edu.iit.sat.itmd4515.adamarjian.service.VideoGameService;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.ConstraintViolation;
import javax.validation.Validator;

/**
 *
 * @author EXO
 */
@WebServlet(name = "PlayerServlet", urlPatterns = {"/player"})
public class PlayerServlet extends HttpServlet {


    @Resource
    Validator validator;

    @EJB
    PlayerService playerSvc;

    @EJB
    VideoGameService vgameSvc;

    private static final Logger LOG = Logger.getLogger(Player.class.getName());

    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet PlayerServlet</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet PlayerServlet at " + request.getContextPath() + "</h1>");
            out.println("<h2>Welcome" + request.getRemoteUser() + "</h2>");
            out.println("<a href=\"" + request.getContextPath() + "/logout\">Logout</a>");

            if (request.isUserInRole("PLAYER_ROLE")) {
                Player player = playerSvc.findByUserName(request.getRemoteUser());
                out.println("<h2>" + player.getUser().getUserName() + ": " + player.getName() + "</h2>");
                out.println("<h2>Birthday: " + player.getBirthday() + "</h2>");
                out.println("<h2>Email: " + player.getEmail() + "</h2>");
                out.println("<h2>Bank: " + player.getBank().getName() + "</h2>");
                out.println("<h2>Bank: </h2>");
                out.println("<ul>");
                for (VideoGame vgame : player.getVideogames()) {
                    out.println("<li>" + vgame.getName() + "</li>");
                }
                out.println("</ul>");
            }

            out.println("</body>");
            out.println("</html>");
        }
    }

    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        LOG.info("Inside the doGet method");
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        LOG.info("Inside the doPost method");
        LOG.info("You passed a parameter called name with a value of " + request.getParameter("name"));
        LOG.info("You passed a parameter called email with a value of " + request.getParameter("email"));
        LOG.info("You passed a parameter called dateHired with a value of " + request.getParameter("dateHired"));

        String nameParam = request.getParameter("name");
        String emailParam = request.getParameter("email");
        String birthdayParam = request.getParameter("birthday");

        Date parsedDate = null;
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        if (!birthdayParam.isEmpty()) {
            try {
                parsedDate = format.parse(birthdayParam);
            } catch (ParseException ex) {
                LOG.log(Level.SEVERE, null, ex);
            }
        }

        LOG.info("The length of |"
                + nameParam
                + "| is "
                + nameParam.length()
                + " and isEmpty returns "
                + nameParam.isEmpty()
        );

        Player player = new Player(nameParam, emailParam, parsedDate);
        LOG.info(player.toString());

        Set<ConstraintViolation<Player>> constraintViolations = validator.validate(player);
        if (constraintViolations.size() > 0) {
            LOG.info("We have an issue Failed validation");
            for (ConstraintViolation<Player> bad : constraintViolations) {
                LOG.info(bad.getPropertyPath() + " " + bad.getMessage());
            }

            request.setAttribute("player", player);
            if (player.getBirthday()!= null) {
                request.setAttribute("birthday", format.format(player.getBirthday()));
            }
            request.setAttribute("errors", constraintViolations);
            RequestDispatcher dispatcher = request.getRequestDispatcher("/WEB-INF/newplayerform.jsp");
            dispatcher.forward(request, response);

        } else {
            LOG.info("No problems with user input.  Proceed.");
            request.setAttribute("player", player);
            RequestDispatcher dispatcher = request.getRequestDispatcher("/WEB-INF/confirm.jsp");
            dispatcher.forward(request, response);
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }
}

src/main/webapp/player/editGame.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/template/portalTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Video Game
    </ui:define>

    <ui:define name="content">
        <ezcomp:show show="#{playerController.videoGame}" 
                     readonly="false" 
                     action="#{playerController.executeSaveVideoGame()}"/>
    </ui:define>

</ui:composition>

src/main/webapp/player/viewGame.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/template/portalTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Video Game
    </ui:define>

    <ui:define name="content">
        <ezcomp:show show="#{playerController.videoGame}" readonly="true" />
    </ui:define>

</ui:composition>

src/main/webapp/player/welcome.jsp
<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>

        <h1>ServletContext (pageContext.servletContext)</h1>
        <h2>Player Home</h2>
        <table border=1>
            <tr>
                <th>Name</th>
                <th>Value</th>
            </tr>
            <tr>
                <td><c:out value="Context Path" /></td>
                <td><c:out value="${pageContext.servletContext.contextPath}" /></td>
            </tr>
            <tr>
                <td><c:out value="Effective Major Version" /></td>
                <td><c:out value="${pageContext.servletContext.effectiveMajorVersion}" /></td>
            </tr>
            <tr>
                <td><c:out value="Effective Minor Version" /></td>
                <td><c:out value="${pageContext.servletContext.effectiveMinorVersion}" /></td>
            </tr>
            <tr>
                <td><c:out value="Major Version" /></td>
                <td><c:out value="${pageContext.servletContext.majorVersion}" /></td>
            </tr>
            <tr>
                <td><c:out value="Minor Version" /></td>
                <td><c:out value="${pageContext.servletContext.minorVersion}" /></td>
            </tr>
            <tr>
                <td><c:out value="Server Info" /></td>
                <td><c:out value="${pageContext.servletContext.serverInfo}" /></td>
            </tr>
            <tr>
                <td><c:out value="Servlet Context Name" /></td>
                <td><c:out value="${pageContext.servletContext.servletContextName}" /></td>
            </tr>
            <tr>
                <td><c:out value="Virtual Server Name" /></td>
                <td><c:out value="${pageContext.servletContext.virtualServerName}" /></td>
            </tr>
        </table>        
        
        <h1>ServletRequest (pageContext.request)</h1>
        <table border=1>
            <tr>
                <th>Name</th>
                <th>Value</th>
            </tr>
            <tr>
                <td><c:out value="Character Encoding" /></td>
                <td><c:out value="${pageContext.request.characterEncoding}" /></td>
            </tr>
            <tr>
                <td><c:out value="Content Length" /></td>
                <td><c:out value="${pageContext.request.contentLength}" /></td>
            </tr>
            <tr>
                <td><c:out value="Content Type" /></td>
                <td><c:out value="${pageContext.request.contentType}" /></td>
            </tr>
            <tr>
                <td><c:out value="Local Address" /></td>
                <td><c:out value="${pageContext.request.localAddr}" /></td>
            </tr>
            <tr>
                <td><c:out value="Local Name" /></td>
                <td><c:out value="${pageContext.request.localName}" /></td>
            </tr>
            <tr>
                <td><c:out value="Local Port" /></td>
                <td><c:out value="${pageContext.request.localPort}" /></td>
            </tr>
            <tr>
                <td><c:out value="Locale" /></td>
                <td><c:out value="${pageContext.request.locale}" /></td>
            </tr>
            <tr>
                <td><c:out value="Protocol" /></td>
                <td><c:out value="${pageContext.request.protocol}" /></td>
            </tr>
            <tr>
                <td><c:out value="Remote Address" /></td>
                <td><c:out value="${pageContext.request.remoteAddr}" /></td>
            </tr>
            <tr>
                <td><c:out value="Remote Host" /></td>
                <td><c:out value="${pageContext.request.remoteHost}" /></td>
            </tr>
            <tr>
                <td><c:out value="Remote Port" /></td>
                <td><c:out value="${pageContext.request.remotePort}" /></td>
            </tr>
            <tr>
                <td><c:out value="Scheme" /></td>
                <td><c:out value="${pageContext.request.scheme}" /></td>
            </tr>
            <tr>
                <td><c:out value="Secure" /></td>
                <td><c:out value="${pageContext.request.secure}" /></td>
            </tr>
            <tr>
                <td><c:out value="Server Name" /></td>
                <td><c:out value="${pageContext.request.serverName}" /></td>
            </tr>
            <tr>
                <td><c:out value="Server Port" /></td>
                <td><c:out value="${pageContext.request.serverPort}" /></td>
            </tr>
        </table>

        <h1>HttpServletRequest (pageContext.request)</h1>
        <table border=1>
            <tr>
                <th>Name</th>
                <th>Value</th>
            </tr>
            <tr>
                <td><c:out value="Auth Type" /></td>
                <td><c:out value="${pageContext.request.authType}" /></td>
            </tr>
            <tr>
                <td><c:out value="Context Path" /></td>
                <td><c:out value="${pageContext.request.contextPath}" /></td>
            </tr>
            <tr>
                <td><c:out value="Method" /></td>
                <td><c:out value="${pageContext.request.method}" /></td>
            </tr>
            <tr>
                <td><c:out value="Path Info" /></td>
                <td><c:out value="${pageContext.request.pathInfo}" /></td>
            </tr>
            <tr>
                <td><c:out value="Path Translated" /></td>
                <td><c:out value="${pageContext.request.pathTranslated}" /></td>
            </tr>
            <tr>
                <td><c:out value="Query String" /></td>
                <td><c:out value="${pageContext.request.queryString}" /></td>
            </tr>
            <tr>
                <td><c:out value="Remote User" /></td>
                <td><c:out value="${pageContext.request.remoteUser}" /></td>
            </tr>
            <tr>
                <td><c:out value="Requested Session Id" /></td>
                <td><c:out value="${pageContext.request.requestedSessionId}" /></td>
            </tr>
            <tr>
                <td><c:out value="Request URI" /></td>
                <td><c:out value="${pageContext.request.requestURI}" /></td>
            </tr>
            <tr>
                <td><c:out value="Request URL" /></td>
                <td><c:out value="${pageContext.request.requestURL}" /></td>
            </tr>
            <tr>
                <td><c:out value="Servlet Path" /></td>
                <td><c:out value="${pageContext.request.servletPath}" /></td>
            </tr>
            <tr>
                <td><c:out value="Session ID from Cookie" /></td>
                <td><c:out value="${pageContext.request.requestedSessionIdFromCookie}" /></td>
            </tr>
            <tr>
                <td><c:out value="Session ID from URL" /></td>
                <td><c:out value="${pageContext.request.requestedSessionIdFromURL}" /></td>
            </tr>
        </table>

        <h1>ServletResponse (pageContext.response)</h1>
        <table border=1>
            <tr>
                <th>Name</th>
                <th>Value</th>
            </tr>
            <tr>
                <td><c:out value="Character Encoding" /></td>
                <td><c:out value="${pageContext.response.characterEncoding}" /></td>
            </tr>
            <tr>
                <td><c:out value="Content Type" /></td>
                <td><c:out value="${pageContext.response.contentType}" /></td>
            </tr>
            <tr>
                <td><c:out value="Locale" /></td>
                <td><c:out value="${pageContext.response.locale}" /></td>
            </tr>
            <tr>
                <td><c:out value="Committed" /></td>
                <td><c:out value="${pageContext.response.committed}" /></td>
            </tr>
        </table>

        <h1>HttpServletResponse (pageContext.response)</h1>
        <table border=1>
            <tr>
                <th>Name</th>
                <th>Value</th>
            </tr>
            <tr>
                <td><c:out value="Status" /></td>
                <td><c:out value="${pageContext.response.status}" /></td>
            </tr>
        </table>

        <c:if test="${not empty header}">
            <h1>HTTP Headers</h1>
            <table border=1>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
                <c:forEach var="nextHeader" items="${header}">
                    <tr>
                        <td><c:out value="${nextHeader.key}" /></td>
                        <td><c:out value="${nextHeader.value}" /></td>
                    </tr>
                </c:forEach>
            </table>
        </c:if>
        <c:if test="${not empty cookie}">
            <h1>Cookies</h1>
            <table border=1>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
                <c:forEach var="nextCookie" items="${cookie}">
                    <tr>
                        <td><c:out value="${nextCookie.key}" /></td>
                        <td><c:out value="${nextCookie.value.value}" /></td>
                    </tr>
                </c:forEach>
            </table>        
        </c:if>
        <c:if test="${not empty initParam}">
            <h1>Initialization Parameters</h1>
            <table border=1>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
                <c:forEach var="nextParam" items="${initParam}">
                    <tr>
                        <td><c:out value="${nextParam.key}" /></td>
                        <td><c:out value="${nextParam.value}" /></td>
                    </tr>
                </c:forEach>
            </table>
        </c:if>
        <c:if test="${not empty param}">
            <h1>Request Parameters</h1>
            <table border=1>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
                <c:forEach var="nextParam" items="${param}">
                    <tr>
                        <td><c:out value="${nextParam.key}" /></td>
                        <td><c:out value="${nextParam.value}" /></td>
                    </tr>
                </c:forEach>
            </table>
        </c:if>
        <c:if test="${not empty pageScope}">
            <h1>Page Scope Attributes</h1>
            <table border=1>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
                <c:forEach var="nextAttr" items="${pageScope}">
                    <tr>
                        <td><c:out value="${nextAttr.key}" /></td>
                        <td><c:out value="${nextAttr.value}" /></td>
                    </tr>
                </c:forEach>
            </table>
        </c:if>
        <c:if test="${not empty requestScope}">
            <h1>Request Scope Attributes</h1>
            <table border=1>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
                <c:forEach var="nextAttr" items="${requestScope}">
                    <tr>
                        <td><c:out value="${nextAttr.key}" /></td>
                        <td><c:out value="${nextAttr.value}" /></td>
                    </tr>
                </c:forEach>
            </table>
        </c:if>
        <c:if test="${not empty sessionScope}">
            <h1>Session Scope Attributes</h1>
            <table border=1>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
                <c:forEach var="nextAttr" items="${sessionScope}">
                    <tr>
                        <td><c:out value="${nextAttr.key}" /></td>
                        <td><c:out value="${nextAttr.value}" /></td>
                    </tr>
                </c:forEach>
            </table>
        </c:if>
        <c:if test="${not empty applicationScope}">
            <h1>Application Scope Attributes</h1>
            <table border=1>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
                <c:forEach var="nextAttr" items="${applicationScope}">
                    <tr>
                        <td><c:out value="${nextAttr.key}" /></td>
                        <td><c:out value="${nextAttr.value}" /></td>
                    </tr>
                </c:forEach>
            </table>
        </c:if>

    </body>
</html>